CREATE TABLE `T_COMMON_RESOURCE` (
  `ID` INT(11) NOT NULL,
	`RESNAME` VARCHAR(20) ,
	`RECOLOMUN` VARCHAR(20) ,
	`ISWRITABLE` VARCHAR(20) ,
	`TABLENAME` VARCHAR(20) ,
	`CONDITION` VARCHAR(20) ,
	`RESV1` VARCHAR(20) ,
	`RESV2` VARCHAR(20) ,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;